// Reservation actions
export const RESERVATION_CREATE_SUCCESS = 'RESERVATION_CREATE_SUCCESS';
export const RESERVATION_CREATE_FAILURE = 'RESERVATION_CREATE_FAILURE';

export const FETCH_USER_RESERVATIONS_SUCCESS = 'FETCH_USER_RESERVATIONS_SUCCESS';
export const FETCH_USER_RESERVATIONS_FAILURE = 'FETCH_USER_RESERVATIONS_FAILURE';

export const DELETE_RESERVATION_REQUEST = 'DELETE_RESERVATION_REQUEST';
export const DELETE_RESERVATION_SUCCESS = 'DELETE_RESERVATION_SUCCESS';
export const DELETE_RESERVATION_FAILURE = 'DELETE_RESERVATION_FAILURE';
